<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-12-03T19:38:05 IST" name="Suite" finished-at="2021-12-03T19:43:26 IST" duration-ms="320330">
    <groups>
    </groups>
    <test started-at="2021-12-03T19:38:05 IST" name="Test.4" finished-at="2021-12-03T19:38:05 IST" duration-ms="21">
    </test> <!-- Test.4 -->
    <test started-at="2021-12-03T19:38:05 IST" name="Test.5" finished-at="2021-12-03T19:41:54 IST" duration-ms="228154">
      <class name="Mavenfinal.TestFlighttcketbooking">
        <test-method signature="FlightTicketbook()[pri:0, instance:Mavenfinal.TestFlighttcketbooking@7c7d3c46]" started-at="2021-12-03T19:38:06 IST" name="FlightTicketbook" finished-at="2021-12-03T19:41:24 IST" duration-ms="198157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FlightTicketbook -->
        <test-method is-config="true" signature="teardrops()[pri:0, instance:Mavenfinal.TestFlighttcketbooking@7c7d3c46]" started-at="2021-12-03T19:41:25 IST" name="teardrops" finished-at="2021-12-03T19:41:54 IST" duration-ms="28663" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardrops -->
      </class> <!-- Mavenfinal.TestFlighttcketbooking -->
    </test> <!-- Test.5 -->
    <test started-at="2021-12-03T19:38:05 IST" name="Test.3" finished-at="2021-12-03T19:41:59 IST" duration-ms="233273">
      <class name="Mavenfinal.TestRegistration">
        <test-method signature="Registration()[pri:0, instance:Mavenfinal.TestRegistration@f6c03cb]" started-at="2021-12-03T19:38:06 IST" name="Registration" finished-at="2021-12-03T19:41:30 IST" duration-ms="204462" status="FAIL">
          <exception class="org.openqa.selenium.remote.UnreachableBrowserException">
            <message>
              <![CDATA[Error communicating with the remote browser. It may have died.
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DESKTOP-LPJ0J81', ip: '192.168.43.111', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [c4a1046bbe5fd1baa758b1a909047f41, get {url=https://rahulshettyacademy.com/#/index}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 96.0.4664.45, chrome: {chromedriverVersion: 95.0.4638.69 (6a1600ed572fe..., userDataDir: C:\Users\wins\AppData\Local...}, goog:chromeOptions: {debuggerAddress: localhost:62176}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:62176/devtoo..., se:cdpVersion: 96.0.4664.45, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: c4a1046bbe5fd1baa758b1a909047f41]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DESKTOP-LPJ0J81', ip: '192.168.43.111', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [c4a1046bbe5fd1baa758b1a909047f41, get {url=https://rahulshettyacademy.com/#/index}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 96.0.4664.45, chrome: {chromedriverVersion: 95.0.4638.69 (6a1600ed572fe..., userDataDir: C:\Users\wins\AppData\Local...}, goog:chromeOptions: {debuggerAddress: localhost:62176}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:62176/devtoo..., se:cdpVersion: 96.0.4664.45, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: c4a1046bbe5fd1baa758b1a909047f41
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:583)
at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:328)
at Mavenfinal.TestRegistration.Registration(TestRegistration.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: NettyHttpHandler request execution error
at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:83)
at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$6(RetryRequest.java:82)
at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$7(RetryRequest.java:82)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$6(RetryRequest.java:82)
at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$7(RetryRequest.java:82)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:108)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:181)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:164)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:139)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
... 25 more
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to localhost/127.0.0.1:61690 after 180000 ms
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2092)
at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:66)
... 53 more
Caused by: java.util.concurrent.TimeoutException: Request timeout to localhost/127.0.0.1:61690 after 180000 ms
at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
... 1 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.remote.UnreachableBrowserException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Registration -->
        <test-method is-config="true" signature="teardrops()[pri:0, instance:Mavenfinal.TestRegistration@f6c03cb]" started-at="2021-12-03T19:41:49 IST" name="teardrops" finished-at="2021-12-03T19:41:59 IST" duration-ms="10018" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardrops -->
      </class> <!-- Mavenfinal.TestRegistration -->
    </test> <!-- Test.3 -->
    <test started-at="2021-12-03T19:38:05 IST" name="Test.1" finished-at="2021-12-03T19:41:59 IST" duration-ms="233942">
      <class name="Mavenfinal.TestLogin">
        <test-method signature="Validatelogin()[pri:0, instance:Mavenfinal.TestLogin@42a9e5d1]" started-at="2021-12-03T19:38:06 IST" name="Validatelogin" finished-at="2021-12-03T19:41:51 IST" duration-ms="225763" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validatelogin -->
        <test-method is-config="true" signature="teardrops()[pri:0, instance:Mavenfinal.TestLogin@42a9e5d1]" started-at="2021-12-03T19:41:51 IST" name="teardrops" finished-at="2021-12-03T19:41:59 IST" duration-ms="8049" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardrops -->
      </class> <!-- Mavenfinal.TestLogin -->
    </test> <!-- Test.1 -->
    <test started-at="2021-12-03T19:38:05 IST" name="Test.2" finished-at="2021-12-03T19:43:26 IST" duration-ms="320305">
      <class name="Mavenfinal.TestPractisepage">
        <test-method signature="Practise1()[pri:0, instance:Mavenfinal.TestPractisepage@533377b]" started-at="2021-12-03T19:38:06 IST" name="Practise1" finished-at="2021-12-03T19:41:39 IST" duration-ms="213980" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Practise1 -->
        <test-method signature="Practise2()[pri:0, instance:Mavenfinal.TestPractisepage@533377b]" started-at="2021-12-03T19:41:40 IST" name="Practise2" finished-at="2021-12-03T19:43:24 IST" duration-ms="104756" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
The link with textBroken Linkis broken with code404 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
The link with textBroken Linkis broken with code404 expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Mavenfinal.TestPractisepage.Practise2(TestPractisepage.java:135)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Practise2 -->
        <test-method is-config="true" signature="teardrops()[pri:0, instance:Mavenfinal.TestPractisepage@533377b]" started-at="2021-12-03T19:43:25 IST" name="teardrops" finished-at="2021-12-03T19:43:26 IST" duration-ms="542" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardrops -->
      </class> <!-- Mavenfinal.TestPractisepage -->
    </test> <!-- Test.2 -->
  </suite> <!-- Suite -->
</testng-results>
